version: '3.6'
volumes:
  zksingle-ksingle_broker-data:
  zksingle-ksingle_broker-secrets:
  zksingle-ksingle_zookeeper-data:
  zksingle-ksingle_zookeeper-log:
  zksingle-ksingle_zookeeper-secrets:
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    hostname: zookeeper
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
    - type: volume
      source: zksingle-ksingle_zookeeper-data
      target: /var/lib/zookeeper/data
    - type: volume
      source: zksingle-ksingle_zookeeper-log
      target: /var/lib/zookeeper/log
    - type: volume
      source: zksingle-ksingle_zookeeper-secrets
      target: /etc/zookeeper/secrets
    ports:
      - 2181:2181
  
  kafka:
    image: confluentinc/cp-kafka:latest
    hostname: kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
    - type: volume
      source: zksingle-ksingle_broker-data
      target: /var/lib/kafka/data
    - type: volume
      source: zksingle-ksingle_broker-secrets
      target: /etc/kafka/secrets